### ISSUE TITLE
Attributes added to VideoBg tag

### ISSUE THREAD

**Issue by Agent9G** [samAbeywickrama/reactjs-videobg#2]
How am i to add attributes to this tag.

i currently have such:
`<VideoBg loop={false} muted={false} poster={...}>`

I am getting the warning fro both
'Failed prop type: Invalid prop `loop`of type `boolean`supplied to `j`, expected `string`.

**Comment by Agent9G** [comment]
The other thing, is it possible to make the poster show after the video has played?

**Comment by samAbeywickrama** [comment]
> How am i to add attributes to this tag.
> 
> i currently have such:
> `<VideoBg loop={false} muted={false} poster={...}>`
> 
> I am getting the warning fro both
> 'Failed prop type: Invalid prop `loop`of type `boolean`supplied to `j`, expected `string`.

This is caused by wrong proptype validation in https://github.com/samAbeywickrama/reactjs-videobg/blob/master/src/VideoBg.js 😅

```
  loop: PropTypes.string,
```

It has to be 
```
  loop: PropTypes.bool,
```

I will add a fix this and do a release asap :)

**Comment by samAbeywickrama** [comment]
> The other thing, is it possible to make the poster show after the video has played?

This is not supported, Planing to implement this soon :)

**Comment by samAbeywickrama** [comment]
> How am i to add attributes to this tag.
> 
> i currently have such:
> `<VideoBg loop={false} muted={false} poster={...}>`
> 
> I am getting the warning fro both
> 'Failed prop type: Invalid prop `loop`of type `boolean`supplied to `j`, expected `string`.

I have done a silly mistake in  proptype validation in https://github.com/samAbeywickrama/reactjs-videobg/blob/master/src/VideoBg.js 😅

```
  loop: PropTypes.string,
```

It has to be 
```
  loop: PropTypes.bool,
```

I will add a fix to this and do a release asap :)

**Comment by rasulacaldera** [comment]
> > The other thing, is it possible to make the poster show after the video has played?
> 
> This is not supported, Planing to implement this soon :)

Working on this here [#4](https://github.com/samAbeywickrama/reactjs-videobg/issues/4)

**Comment by Agent9G** [comment]
> > The other thing, is it possible to make the poster show after the video has played?
> 
> This is not supported, Planing to implement this soon :)

Solid!

**Comment by Agent9G** [comment]
> > How am i to add attributes to this tag.
> > i currently have such:
> > `<VideoBg loop={false} muted={false} poster={...}>`
> > I am getting the warning fro both
> > 'Failed prop type: Invalid prop `loop`of type `boolean`supplied to `j`, expected `string`.
> 
> I have done a silly mistake in proptype validation in https://github.com/samAbeywickrama/reactjs-videobg/blob/master/src/VideoBg.js 
> 
> ```
>   loop: PropTypes.string,
> ```
> 
> It has to be
> 
> ```
>   loop: PropTypes.bool,
> ```
> 
> I will add a fix to this and do a release asap :)

You da champ! 

Thank you.
